### ISSUE TITLE
Failed loading atom-sfdc-utils

### ISSUE THREAD

**Issue by magandrez** [CodisRedding/atom-sfdc-utils#1]
Hi,

I've tried to install this package and tested it but I could't get to insert my SFDC credentials. When I opened Atom on dev mode and I inspected the logs I found atom-sfdc-utils gives an error when activating the package:

`Failed to activate package named 'atom-sfdc-utils' /Users/Manuel/.atom/packages/atom-sfdc-utils/lib/salesforce-meta.coffee:71:15: error: unexpected indentation`

Any clue why?

-Manuel

**Comment by CodisRedding** [comment]
I'll take a look now.

**Comment by CodisRedding** [comment]
I'll have a look at this tonight. I couldn't figure out the issue. I ran the linter, found the indent issue, but that didn't resolve it.

**Comment by agentgill** [comment]
I'm getting the same issue
